import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Get user's Google Calendar connection
    const CONNECTOR_ID = '69e7a7202687f45218c44281'; // User Google Calendar
    
    try {
      const { accessToken } = await base44.asServiceRole.connectors.getCurrentAppUserConnection(CONNECTOR_ID);

      // Fetch upcoming events for today and tomorrow
      const now = new Date();
      const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000);
      
      const timeMin = now.toISOString();
      const timeMax = tomorrow.toISOString();

      const response = await fetch(
        `https://www.googleapis.com/calendar/v3/calendars/primary/events?timeMin=${encodeURIComponent(timeMin)}&timeMax=${encodeURIComponent(timeMax)}&singleEvents=true&orderBy=startTime`,
        {
          headers: { Authorization: `Bearer ${accessToken}` },
        }
      );

      const calendar = await response.json();
      const events = calendar.items || [];

      if (events.length === 0) {
        return Response.json({ message: 'No upcoming meetings', sent: false });
      }

      // Format events for summary
      const eventList = events
        .map(e => `• ${e.summary} (${new Date(e.start.dateTime || e.start.date).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true })})`)
        .join('\n');

      // Generate AI summary
      const summary = await base44.integrations.Core.InvokeLLM({
        prompt: `Generate a brief, helpful summary of these upcoming meetings for an executive's morning. Focus on key themes, priorities, and any major decisions or discussions. Keep it to 2-3 sentences max.

Meetings:
${eventList}`,
      });

      // Send email with summary
      const html = `
      <html>
        <head>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1e293b; }
            .header { background: linear-gradient(135deg, #071520 0%, #0a1f2e 100%); color: #00e5c8; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
            .header h1 { margin: 0; font-size: 20px; }
            .summary { background: #f0fdf4; border-left: 4px solid #22c55e; padding: 15px; border-radius: 6px; margin-bottom: 20px; }
            .summary p { margin: 0; color: #1e293b; line-height: 1.6; }
            .meetings { margin-top: 20px; }
            .meetings h2 { font-size: 14px; color: #334155; margin: 0 0 10px 0; }
            .meeting { background: #f8fafc; border-left: 3px solid #00e5c8; padding: 10px 12px; margin-bottom: 8px; border-radius: 4px; }
            .meeting p { margin: 0; font-size: 13px; color: #1e293b; }
            .meeting-time { font-size: 12px; color: #64748b; margin-top: 4px; }
            .footer { border-top: 1px solid #e2e8f0; padding-top: 15px; font-size: 12px; color: #64748b; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>📅 Morning Meeting Summary</h1>
            <p>${new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</p>
          </div>

          <div class="summary">
            <p><strong>Executive Brief:</strong> ${summary}</p>
          </div>

          <div class="meetings">
            <h2>Today's Meetings (${events.length})</h2>
            ${events.map(e => `
              <div class="meeting">
                <p><strong>${e.summary}</strong></p>
                <div class="meeting-time">
                  ${new Date(e.start.dateTime || e.start.date).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true })}
                  ${e.location ? ` • ${e.location}` : ''}
                </div>
              </div>
            `).join('')}
          </div>

          <div class="footer">
            <p>Generated by EDS Executive Hub • Emerging Defense Solutions</p>
          </div>
        </body>
      </html>
      `;

      await base44.integrations.Core.SendEmail({
        to: user.email,
        subject: `📅 Morning Meeting Summary — ${events.length} meeting${events.length > 1 ? 's' : ''} today`,
        body: html,
        from_name: 'EDS Executive Hub',
      });

      return Response.json({ sent: true, meeting_count: events.length, summary });
    } catch (calendarError) {
      // Calendar not connected, return gracefully
      return Response.json({ message: 'Google Calendar not connected. Connect to enable meeting summaries.', connected: false });
    }
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});