import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    // Fetch critical incidents from the last 24 hours
    const now = new Date();
    const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);

    const [stigs, vulns, incidents] = await Promise.all([
      base44.asServiceRole.entities.STIGFinding.filter({ status: 'open', severity: 'CAT_I' }, '-created_date', 50),
      base44.asServiceRole.entities.VulnerabilityFinding.filter({ status: 'open', severity: 'critical' }, '-created_date', 50),
      base44.asServiceRole.entities.Incident.filter({ severity: 'critical', status: 'open' }, '-created_date', 50),
    ]);

    const recentStigs = stigs.filter(s => new Date(s.created_date) > yesterday);
    const recentVulns = vulns.filter(v => new Date(v.created_date) > yesterday);
    const recentIncidents = incidents.filter(i => new Date(i.detected_at) > yesterday);

    const totalCritical = recentStigs.length + recentVulns.length + recentIncidents.length;

    if (totalCritical === 0) {
      return Response.json({ message: 'No critical incidents in last 24 hours' });
    }

    const html = `
    <html>
      <head>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1e293b; }
          .header { background: linear-gradient(135deg, #071520 0%, #0a1f2e 100%); color: #00e5c8; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
          .header h1 { margin: 0; font-size: 24px; }
          .header p { margin: 5px 0 0 0; font-size: 14px; color: #cbd5e1; }
          .section { margin-bottom: 20px; }
          .section h2 { color: #ef4444; font-size: 16px; margin: 0 0 10px 0; }
          .item { background: #f8fafc; border-left: 3px solid #ef4444; padding: 10px 12px; margin-bottom: 8px; border-radius: 4px; }
          .item p { margin: 0; font-size: 13px; }
          .item-title { font-weight: 600; color: #1e293b; }
          .item-meta { font-size: 12px; color: #64748b; margin-top: 4px; }
          .footer { border-top: 1px solid #e2e8f0; padding-top: 15px; font-size: 12px; color: #64748b; }
          .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; margin-right: 4px; }
          .badge-critical { background: #fecaca; color: #7f1d1d; }
          .badge-cat1 { background: #fca5a5; color: #7f1d1d; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>🚨 Critical Security Summary</h1>
          <p>${now.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}</p>
        </div>

        ${recentIncidents.length > 0 ? `
          <div class="section">
            <h2>Security Incidents (${recentIncidents.length})</h2>
            ${recentIncidents.map(i => `
              <div class="item">
                <p class="item-title"><span class="badge badge-critical">CRITICAL</span>${i.title}</p>
                <p class="item-meta">Category: ${i.category?.replace(/_/g, ' ')} | Status: ${i.status?.replace(/_/g, ' ')}</p>
              </div>
            `).join('')}
          </div>
        ` : ''}

        ${recentVulns.length > 0 ? `
          <div class="section">
            <h2>Critical Vulnerabilities (${recentVulns.length})</h2>
            ${recentVulns.map(v => `
              <div class="item">
                <p class="item-title"><span class="badge badge-critical">${v.cve_id || 'CVE'}</span>${v.title}</p>
                <p class="item-meta">CVSS: ${v.cvss_score || '—'} | Asset: ${v.asset_hostname || '—'}</p>
              </div>
            `).join('')}
          </div>
        ` : ''}

        ${recentStigs.length > 0 ? `
          <div class="section">
            <h2>CAT I STIG Findings (${recentStigs.length})</h2>
            ${recentStigs.map(s => `
              <div class="item">
                <p class="item-title"><span class="badge badge-cat1">${s.stig_id}</span>${s.title}</p>
                <p class="item-meta">Asset: ${s.asset_hostname || '—'} | Status: ${s.status?.replace(/_/g, ' ')}</p>
              </div>
            `).join('')}
          </div>
        ` : ''}

        <div class="footer">
          <p>Total Critical Items: <strong>${totalCritical}</strong></p>
          <p>Generated by EDS Eye Dashboard • Emerging Defense Solutions</p>
        </div>
      </body>
    </html>
    `;

    await base44.integrations.Core.SendEmail({
      to: (await base44.auth.me()).email,
      subject: `🚨 EDS Critical Security Alert — ${recentIncidents.length + recentVulns.length + recentStigs.length} Items`,
      body: html,
      from_name: 'EDS Dashboard',
    });

    return Response.json({ sent: true, critical_count: totalCritical });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});